# Generated by Django 3.0.7 on 2020-10-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201006_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$180000$V0u9CLVr79Oa$EwlNZ4A64fEIAXKRXcltAuhmJJYZF7HXsgoy86DLQcE=', max_length=100),
        ),
    ]
