# Generated by Django 3.0.7 on 2020-10-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allDay',
            field=models.BooleanField(default=False),
        ),
    ]
