# Generated by Django 3.0.7 on 2020-10-12 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_event_allday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.AddField(
            model_name='event',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='teacher_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Math'), (2, 'Physics'), (3, 'English')], default=1),
        ),
    ]
