# Generated by Django 3.0.7 on 2020-10-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201012_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.PositiveSmallIntegerField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('English', 'English')], default=1),
        ),
    ]
