# Generated by Django 3.0.7 on 2020-10-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201012_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('English', 'English')]),
        ),
    ]
